### PR TITLE
Infrastructure: Adds pkgdown site, CI testing

### PR DESCRIPTION
**Pull request by cboettig**

### CODE REVIEW

**Comment by cboettig** [comment]
@mdietze @ashiklom @rqthomas lemme know if someone can give this a quick review and merge. (pkgdown site won't display until we merge, though you could preview locally).  No substantive changes here though, just added GitHub Actions for some CI checks which will make sure the vignettes build, and a bit of house cleaning to avoid a few warnings.  Checks should appear above.  

Mostly thought it would be nice to have some HTML-rendered vignettes we can link to if need be and some basic CI.

**Review by ashiklom — APPROVED** [review]
Just skimmed through. Looks good to me!

**Comment by mdietze** [comment]
Agree. Looks good. One thing to keep an eye on is that I found that the diff on the csv and netcdf still seemed to be changing for me even though all the contents  of the files didn't actually to be changing (set seed and forecast ID so every execution should be identical)

**Comment by cboettig** [comment]
@ashiklom @mdietze thanks!

Re the changing `.csv` I'll have to do some splunking to see why those are still changing. 

However, note that we're no longer re-committing the `.csv` output files that get generated anyway.  `R CMD check` doesn't like having additional files in the `vignettes` directory (they don't get copied over into `inst/doc when the package is built and can create problems when people are copy-pasting lines from the vignette to run themselves), so I've moved all those files into `inst/extdata`, and added a line to the vignettes  to silently clean up after they run (though technically I believe CRAN wants them to write to tempdir these days instead of writing and removing files in whatever the current working directory might be).  long story short, re-rendering vignettes at least won't bloat the repo.

**Pull request merged**
